#!/usr/bin/env bash
set -Eeuo pipefail

suite='stretch'
timestamp='2017-01-01T00:00:00Z'

expectedEpoch='1483228800'

declare -A expectedSha256s=(
	['amd64']='26490ed3400a5029b8b5939c6cebd38691e28ea5c616bb54f25f758125417c5f'
	['arm64']='45e5e0c6da27db14de19a600663140db1f85f7516a856bf00957436e93e1f684'
	['armel']='9935d1ffc1316d9a03b223225f909e6d229f96a437b49a23abb1e33406c43e3d'
	['armhf']='feaef36fd7a5e202a426099b5e110d91da234f17c63b77ac7169d3da21079878'
	['i386']='800eb45aa8d0f8132533832cd4483dab47450ef86fb86874d9a2994616c4f3a1'
	['mips64el']='63ceab271ebaacc8036f3790a7ac206e4f6662cfb5669be00889993f14a82abe'
	['ppc64el']='31876452b695db0843cf81a48b0a236edf52c5eb68e730d8e041383ed511e7cc'
	['s390x']='587779b5c2f8defaa2de40755193c814358db34a1f3c82d68038a1ae226ccff3'
)
dpkgArch="$(dpkg --print-architecture)"
expectedSha256="${expectedSha256s["$dpkgArch"]:-}"

tempDir="$(mktemp -d)"
trap "rm -rf '$tempDir'" EXIT
rootfs="$tempDir/rootfs"

set -x

# make a new keyring that contains all archive keys so this still works in the future too
# (see also "debian.sh" in the debuerreotype examples, which this is a hyper-simplified version of)
keyring="$tempDir/keyring.gpg"
gpg --batch --no-default-keyring --keyring "$keyring" --import \
	/usr/share/keyrings/debian-archive-keyring.gpg \
	/usr/share/keyrings/debian-archive-removed-keys.gpg

debuerreotype-init --arch="$dpkgArch" --keyring="$keyring" "$rootfs" "$suite" "$timestamp"
[ "$(< "$rootfs/debuerreotype-epoch")" = "$expectedEpoch" ]

debuerreotype-chroot "$rootfs" true

debuerreotype-debian-sources-list "$rootfs" "$suite"
# remove effect of https://github.com/debuerreotype/debuerreotype/pull/56 (to avoid regenerating expected tarballs to compensate)
sed -i -e '/^#/d' "$rootfs/etc/apt/sources.list"

debuerreotype-tar "$rootfs" "$tempDir/actual.tar"
sha256="$(sha256sum "$tempDir/actual.tar" | cut -d' ' -f1)"

# see https://people.debian.org/~tianon/debuerreotype/

if [ "$sha256" != "$expectedSha256" ]; then
	if [ -z "$expectedSha256" ]; then
		(
			set +x
			echo >&2
			echo >&2 "WARNING: no expected SHA256 for '$dpkgArch' known -- please file a bug with this full build output against src:debuerreotype!"
			echo >&2
		)
		exit 0
	fi

	(
		set +x
		echo >&2
		echo >&2 'ERROR: expected SHA256 does not match actual -- downloading pristine source to compare (via diffoscope)'
		echo >&2
	)

	toCompare="https://people.debian.org/~tianon/debuerreotype/$suite--$timestamp--$dpkgArch--$expectedSha256.txz"
	wget -qO "$tempDir/expected.txz" "$toCompare"
	xz -d < "$tempDir/expected.txz" > "$tempDir/expected.tar"
	diffoscope >&2 "$tempDir/expected.tar" "$tempDir/actual.tar"
	exit 1
fi
